variable = input('Enter Your statement: ')
print(variable.upper())
print(variable.lower())
print(variable.count('josh'))
print(variable.find('josh'))
print(variable.replace('josh','sash'))
print(variable.islower())
print(variable.isupper())
print(variable.isalnum())
print(variable.isalpha())
print(variable.isdigit())
print(variable.index('j'))
print(variable.strip('hm'))
print(variable)
